//
//  Constants.h
//  CommanderLifeCounter
//
//  Created by Vasiliy Egorov on 19.07.17.
//  Copyright © 2017 VasiliyEgorov. All rights reserved.
//


#import <UIKit/UIKit.h>



FOUNDATION_EXPORT float CURRENT_KEYBOARDHEIGHT;
FOUNDATION_EXPORT float const IPHONE_5;
FOUNDATION_EXPORT float const IPHONE_6_7;
FOUNDATION_EXPORT float const IPHONE_6_7_PLUS;
FOUNDATION_EXPORT float const IPHONE_X;
FOUNDATION_EXPORT int const NOCONNECTION;
FOUNDATION_EXPORT NSString *const EMPTY;
FOUNDATION_EXPORT NSString *const NOTEXT;
FOUNDATION_EXPORT NSString *const NOADDITIONALTEXT;
FOUNDATION_EXPORT NSString *const SPACE;
FOUNDATION_EXPORT float const AVATAR_HEIGHT_IPHONE_5;
FOUNDATION_EXPORT float const AVATAR_HEIGHT_IPHONE_6_7;
FOUNDATION_EXPORT float const AVATAR_HEIGHT_IPHONE_6_7_PLUS;
FOUNDATION_EXPORT float const AVATAR_HEIGHT_IPHONE_X;
@interface Constants : NSObject

@end
